name: PHPStan

on: [push]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Composer install
        run: composer install -n

      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@master
        with:
          path: src/ tests/
          level: 9
